language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '10'
  - '9'
  - '8'
  - '6'
notifications:
  email: false
install:
  - npm install
script:
  - npm test
after_success:
  - npm run codecov
